version: '3.3'

services: 
    mysqldb:
        image: mysql:5.7
        container_name: shop-mysql-db
        # If you want to that mysql runs automatically
        restart: always
        environment: 
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'user-password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root-password'
        ports:
            - 3306:3306
            - 33060:33060
        # Where our data will be persisted
        volumes:
        - my-db:/var/lib/mysql
            
# Names our volume
volumes:
    my-db: